### ISSUE TITLE
outer_html () returns incorrect value

### ISSUE THREAD

**Issue by lesssn** [gawel/pyquery#168]
- When the text of the tag is empty, outer_html () outputs self-closing tag, lead to the browser may parse error.
```
>> PyQuery('<a></a>').outer_html()
>> '<a/>'
```

- Look from the source code is use of the etree. Tostring () method, the method of parameter "method" the default value is "XML", when set to 'HTML' can normal parsing
```
 return etree.tostring(e0, encoding=unicode)
```
```
def tostring(element_or_tree, encoding=None, method="xml", xml_declaration=None, pretty_print=False, with_tail=True, standalone=None, doctype=None, exclusive=False, with_comments=True, inclusive_ns_prefixes=None): # real signature unknown; restored from __doc__
```

- I wonder if there should be add the "method" parameter to outer_html() method , used to set the parse format
```
    @with_camel_case_alias
    def outer_html(self, method='html'):
        """Get the html representation of the first selected element::

            >>> d = PyQuery('<div><span class="red">toto</span> rocks</div>')
            >>> print(d('span'))
            <span class="red">toto</span> rocks
            >>> print(d('span').outer_html())
            <span class="red">toto</span>
            >>> print(d('span').outerHtml())
            <span class="red">toto</span>

            >>> S = PyQuery('<p>Only <b>me</b> & myself</p>')
            >>> print(S('b').outer_html())
            <b>me</b>

        ..
        """

        if not self:
            return None
        e0 = self[0]
        if e0.tail:
            e0 = deepcopy(e0)
            e0.tail = ''
        return etree.tostring(e0, encoding=unicode, method=method)
```

**Comment by gawel** [comment]
Good idea. It's done... after a couple monthes... :) Sorry for the lag.

**Comment by bepetersn** [comment]
Hey, I noticed a similar issue with a self-closing tag and realized that maybe `PyQyery.html()` uses a method of 'xml' by default still, whereas with the above commit you changed `outer_html()` to have a default method of 'html'. 

My use case is comparing the results of calling PyQuery.html from a whole page with PyQuery.outer_html on a portion of the page, searching for that portion, and removing it. I was having trouble getting this kind of use case to work because of the above reason. Just a thought.
