### ISSUE TITLE
Constructor is potentially dangerous

### ISSUE THREAD

**Issue by peterbe** [gawel/pyquery#203]
We use PyQuery internally in our system to parse rendered HTML strings that we store in the database to be displayed in a Django web response. Essentially the code looks a bit like this:

```python
def render_document(document):
    parsed = PyQuery(document.rendered_html_string)
    ...
```

But if untrusted users can cause that `document.rendered_html_string` to become a string that looks something like this:

```
http://internaldomain/api/get_users/dangerous
```

Then, it becomes...

```python
def render_document(document):
    parsed = PyQuery('http://internaldomain/api/get_users/dangerous')
   ...
```
which will cause PyQuery to `requests.get('http://internaldomain/api/get_users/dangerous')` which could be a big security risk. 

It happens because of [the constructor](https://github.com/gawel/pyquery/blob/2351446c56d5c3df93e3fd81a2b828cf00e3b648/pyquery/pyquery.py#L190-L196) being too "naive". 

On our app, we solved that by making the PyQuery constructor wrapped in a piece of code that does something like this:

```python
def safer_pyquery(*args, **kwargs):
    # SIMPLIFIED FOR EXAMPLE
    args[0] = ' ' + args[0]
    return PyQuery(*args, **kwargs)
```

Ideally, we'd love to be able to always invoke `PyQuery` like this:

```python
def render_document(document):
    parsed = PyQuery(html=document.rendered_html_string)
    ...
```
In similar style to how you can do `pq(url='http://google.com/')` as mentioned in the Quickstart documentation.

**Comment by gawel** [comment]
I have no problème with that. Feel free to provide a PR if you want.

Something like this should be enough:
```
if 'html' in kwargs:
  kwargs['data'] = kwargs.pop('html')
elif current mess:
```

**Comment by jcushman** [comment]
@gawel, what would you think of changing the default behavior of PyQuery to _not_ look for a url, and only fetch url contents if the user explicitly provides `pq(url='http://google.com/')`?

This would require a new version number, because it's a breaking change, but I think it would be worth it for the security benefits. Most users calling `pq(text)` probably don't want it to make a web request if the text happens to start with 'http', and if users do want that it's easy enough to add `url=`.

If this sounds good to you I'm happy to send a PR!

**Comment by gawel** [comment]
@jcushman seems fine. go for it
